name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19.x"

      - name: Install Dependencies
        run: npm install

      - name: Publish Github Pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/hadynz/linearcycle-pathforward.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
